# Generated by Django 2.0.7 on 2018-08-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposrv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='connection',
            field=models.CharField(blank=True, help_text='Blochchain connectoin', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='interval',
            field=models.IntegerField(blank=True, help_text='Blochchain refresh interval', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.CharField(blank=True, help_text='Customer comments', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kyc',
            field=models.CharField(blank=True, help_text='KYC Data', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='regdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updatedate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='createdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='fieldname',
            field=models.CharField(blank=True, help_text='FieldName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='newvalue',
            field=models.CharField(blank=True, help_text='NewValue', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='objectname',
            field=models.CharField(blank=True, help_text='ObjectName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='oldvalue',
            field=models.CharField(blank=True, help_text='OldValue', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='operations',
            name='createdate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='createdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='result',
            field=models.CharField(blank=True, help_text='Result', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
